# Generated by Django 3.0.5 on 2020-12-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
