# Generated by Django 3.0.5 on 2020-12-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20201228_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.ImageField(upload_to=''),
        ),
    ]
